language: java
dist: bionic
notifications:
  email: false
addons:
  sonarcloud:
    organization: "sylvainhalle-github"
    token:
      secure: HjtgPkvP/SYXeoq6OocIk95kbQqD2aRqughWwlwTkNQ45X6E4oovZP0/jRn7hk7h1ecSanXd4NEp7H00RPtRvKhzFxYk0FF20L3SwaH3UGesGJ7zcg8wxc3/E+QzLpfSoLvF78rHcxoPnw8wxEMUb+a0MWrBeOLCfyvWrUiEAWo=
before_install:
- sudo apt-get install ant-optional
script:
- ant download-deps
- ant
- ant test
- sonar-scanner
